// This file was generated by the storyblok CLI.
// DO NOT MODIFY THIS FILE BY HAND.
import type { ISbStoryData } from "storyblok";
export interface ButtonStoryblok {
  fullWidth?: boolean;
  label?: string;
  component: "button";
  _uid: string;
  [k: string]: any;
}

export interface HeadingStoryblok {
  headline: string;
  renderAs?: "" | "h1" | "h2";
  component: "heading";
  _uid: string;
  [k: string]: any;
}

export interface HeroBannerStoryblok {
  heading: string;
  cta: LinkStoryblok[];
  component: "hero-banner";
  _uid: string;
  [k: string]: any;
}

export interface IconButtonStoryblok {
  component: "icon-button";
  _uid: string;
  [k: string]: any;
}

export type MultilinkStoryblok =
  | {
      id?: string;
      cached_url?: string;
      anchor?: string;
      linktype?: "story";
      target?: "_self" | "_blank";
      story?: {
        name: string;
        created_at?: string;
        published_at?: string;
        id: number;
        uuid: string;
        content?: {
          [k: string]: any;
        };
        slug: string;
        full_slug: string;
        sort_by_date?: null | string;
        position?: number;
        tag_list?: string[];
        is_startpage?: boolean;
        parent_id?: null | number;
        meta_data?: null | {
          [k: string]: any;
        };
        group_id?: string;
        first_published_at?: string;
        release_id?: null | number;
        lang?: string;
        path?: null | string;
        alternates?: any[];
        default_full_slug?: null | string;
        translated_slugs?: null | any[];
        [k: string]: any;
      };
      [k: string]: any;
    }
  | {
      url?: string;
      cached_url?: string;
      anchor?: string;
      linktype?: "asset" | "url";
      target?: "_self" | "_blank";
      [k: string]: any;
    }
  | {
      email?: string;
      linktype?: "email";
      target?: "_self" | "_blank";
      [k: string]: any;
    };

export interface LinkStoryblok {
  label: string;
  whereTo: Exclude<MultilinkStoryblok, {linktype?: "email"} | {linktype?: "asset"}>;
  asButton?: boolean;
  component: "link";
  _uid: string;
  [k: string]: any;
}

export interface AssetStoryblok {
  alt?: string;
  copyright?: string;
  id: number;
  filename: string;
  name: string;
  title?: string;
  focus?: string;
  [k: string]: any;
}

export interface MainNavStoryblok {
  logo: AssetStoryblok;
  mobileLogo: AssetStoryblok;
  links?: (
    | ButtonStoryblok
    | HeadingStoryblok
    | HeroBannerStoryblok
    | IconButtonStoryblok
    | LinkStoryblok
    | MainNavStoryblok
    | ModelStoryblok
    | ModelsStoryblok
    | PageStoryblok
    | ParagraphStoryblok
    | ProductStoryblok
    | TabStoryblok
    | TabsStoryblok
  )[];
  component: "main-nav";
  _uid: string;
  [k: string]: any;
}

export interface ModelStoryblok {
  image: AssetStoryblok;
  name: "" | "Model 1" | "Model 2" | "Model 3";
  description: string;
  linkLabel: string;
  cta: Exclude<MultilinkStoryblok, {linktype?: "email"} | {linktype?: "asset"}>;
  component: "model";
  _uid: string;
  [k: string]: any;
}

export interface ModelsStoryblok {
  models?: ModelStoryblok[];
  component: "models";
  _uid: string;
  [k: string]: any;
}

export interface PageStoryblok {
  body?: (
    | ButtonStoryblok
    | HeadingStoryblok
    | HeroBannerStoryblok
    | IconButtonStoryblok
    | LinkStoryblok
    | MainNavStoryblok
    | ModelStoryblok
    | ModelsStoryblok
    | PageStoryblok
    | ParagraphStoryblok
    | ProductStoryblok
    | TabStoryblok
    | TabsStoryblok
  )[];
  component: "page";
  _uid: string;
  [k: string]: any;
}

export interface ParagraphStoryblok {
  text: string;
  component: "paragraph";
  _uid: string;
  [k: string]: any;
}

export type MultiassetStoryblok = {
  alt?: string;
  copyright?: string;
  id: number;
  filename: string;
  name: string;
  title?: string;
  [k: string]: any;
}[];

export interface ProductStoryblok {
  name: string;
  model: "";
  description: string;
  images: MultiassetStoryblok;
  available?: boolean;
  availableLabel: string;
  unavailableLabel: string;
  component: "product";
  _uid: string;
  [k: string]: any;
}

export interface TabStoryblok {
  label: number | string;
  component: "tab";
  _uid: string;
  [k: string]: any;
}

export interface TabsStoryblok {
  tabs: TabStoryblok[];
  component: "tabs";
  _uid: string;
  [k: string]: any;
}
